# Generated by Django 5.2.6 on 2025-12-22 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VISION', 'Vision Detection'), ('AUDIO', 'Audio Detection')], db_index=True, max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence score between 0 and 1')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_events', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident', '-created_at'], name='ai_engine_a_inciden_b03b81_idx'), models.Index(fields=['event_type', '-created_at'], name='ai_engine_a_event_t_8b4607_idx')],
            },
        ),
    ]
