# Generated by Django 5.2.6 on 2025-12-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('incidents', '0004_beaconincident_panicbuttonincident_reportedincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievent',
            name='beacon_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_events', to='incidents.beaconincident'),
        ),
        migrations.AddField(
            model_name='aievent',
            name='panic_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_events', to='incidents.panicbuttonincident'),
        ),
        migrations.AddField(
            model_name='aievent',
            name='reported_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_events', to='incidents.reportedincident'),
        ),
        migrations.AlterField(
            model_name='aievent',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_events', to='incidents.incident'),
        ),
    ]
