# Generated by Django 5.2.6 on 2025-12-24 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aievent_beacon_incident_aievent_panic_incident_and_more'),
        ('incidents', '0004_beaconincident_panicbuttonincident_reportedincident'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aievent',
            name='ai_engine_a_inciden_b03b81_idx',
        ),
        migrations.RemoveField(
            model_name='aievent',
            name='beacon_incident',
        ),
        migrations.RemoveField(
            model_name='aievent',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='aievent',
            name='panic_incident',
        ),
        migrations.RemoveField(
            model_name='aievent',
            name='reported_incident',
        ),
        migrations.AddField(
            model_name='aievent',
            name='beacon',
            field=models.ForeignKey(blank=True, help_text='Location where AI detected the event', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_events', to='incidents.beacon'),
        ),
        migrations.AlterField(
            model_name='aievent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='aievent',
            index=models.Index(fields=['beacon', '-created_at'], name='ai_engine_a_beacon__1bcc28_idx'),
        ),
        migrations.AddIndex(
            model_name='aievent',
            index=models.Index(fields=['confidence_score', '-created_at'], name='ai_engine_a_confide_d5d51a_idx'),
        ),
    ]
