# Generated by Django 5.2.6 on 2026-01-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_remove_aievent_ai_engine_a_inciden_b03b81_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aievent',
            name='event_type',
            field=models.CharField(choices=[('VIOLENCE', 'Violence Detected'), ('SCREAM', 'Scream Detected')], db_index=True, max_length=20),
        ),
    ]
