"""
Django settings for campus_security project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from decouple import config

# Load .env file
import os
from pathlib import Path
env_file = Path(__file__).resolve().parent.parent / '.env'
if env_file.exists():
    try:
        from dotenv import load_dotenv
        load_dotenv(env_file)
    except ImportError:
        pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(^f17f2)(hva#@6k6p7$8k6i6y74aqz6&&6gpb((v574&c0xjc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Render hosts
ALLOWED_HOSTS = ['*.render.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'storages',
    # Local apps
    'accounts',
    'incidents',
    'security',
    'chat',
    'ai_engine',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Security settings for production
SECURE_SSL_REDIRECT = os.getenv('RENDER', False) == 'True'
SESSION_COOKIE_SECURE = os.getenv('RENDER', False) == 'True'
CSRF_COOKIE_SECURE = os.getenv('RENDER', False) == 'True'
SECURE_HSTS_SECONDS = 31536000 if os.getenv('RENDER', False) == 'True' else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('RENDER', False) == 'True'
SECURE_HSTS_PRELOAD = os.getenv('RENDER', False) == 'True'

ROOT_URLCONF = 'campus_security.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'campus_security' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'campus_security.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Google Cloud Storage Configuration for Image Storage
GS_BUCKET_NAME = config('GS_BUCKET_NAME', default='resq-campus-security')
GS_PROJECT_ID = config('GS_PROJECT_ID', default='gen-lang-client-0117249847')
GS_CREDENTIALS = None  # Will use GOOGLE_APPLICATION_CREDENTIALS env var
# Use signed URLs for temporary access (better security than public access)
GS_QUERYSTRING_AUTH = True  # Use query string auth with signed URLs

# Determine storage backend based on environment
if GS_BUCKET_NAME and GS_PROJECT_ID:
    print("[OK] GOOGLE CLOUD STORAGE CONFIGURED")
    print("   Bucket: {}".format(GS_BUCKET_NAME))
    print("   Project: {}".format(GS_PROJECT_ID))
    print("   Using signed URLs for secure image access")
    DEFAULT_FILE_STORAGE = 'campus_security.storage.PublicGoogleCloudStorage'
    # Media URL for GCS storage - django-storages will handle URL generation
    MEDIA_URL = 'https://storage.googleapis.com/{}/'.format(GS_BUCKET_NAME)
else:
    print("[WARNING] GOOGLE CLOUD STORAGE NOT FULLY CONFIGURED")
    print("   GS_BUCKET_NAME: {}".format(GS_BUCKET_NAME))
    print("   GS_PROJECT_ID: {}".format(GS_PROJECT_ID))
    print("   Using local disk storage as fallback")
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'

# Media files directory in GCS
MEDIA_ROOT = 'media'

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}
