# Generated by Django 5.2.6 on 2025-12-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('incidents', '0004_beaconincident_panicbuttonincident_reportedincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='beacon_incident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='incidents.beaconincident'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='panic_incident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='incidents.panicbuttonincident'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='reported_incident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='incidents.reportedincident'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='incident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='incidents.incident'),
        ),
    ]
