# Generated by Django 5.2.6 on 2025-12-24 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_beacon_incident_and_more'),
        ('incidents', '0004_beaconincident_panicbuttonincident_reportedincident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='beacon_incident',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='panic_incident',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='reported_incident',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='incident',
            field=models.OneToOneField(help_text='One conversation per incident', on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='incidents.incident'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['incident'], name='chat_conver_inciden_98ca4f_idx'),
        ),
    ]
