# Generated by Django 5.2.6 on 2026-01-01 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_device'),
        ('incidents', '0012_incident_assigned_at_incident_current_assigned_guard_and_more'),
        ('security', '0007_remove_devicetoken_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_token', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('GUARD_ALERT', 'Guard Alert'), ('ASSIGNMENT_CONFIRMED', 'Assignment Confirmed'), ('NEW_CHAT_MESSAGE', 'New Chat Message'), ('INCIDENT_ESCALATED', 'Incident Escalated'), ('INCIDENT_RESOLVED', 'Incident Resolved')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('INVALID_TOKEN', 'Invalid Token')], db_index=True, default='QUEUED', max_length=20)),
                ('expo_ticket_id', models.CharField(blank=True, help_text='From Expo API response', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Max retry attempts allowed')),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Push Notification Log',
                'verbose_name_plural': 'Push Notification Logs',
                'db_table': 'accounts_push_notification_log',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='accounts_de_user_id_3a43c8_idx',
            old_name='accounts_de_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='accounts_de_token_e678b5_idx',
            old_name='accounts_de_token_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='accounts_de_platfor_e50422_idx',
            old_name='accounts_de_platfor_g7h8i9_idx',
        ),
        migrations.AddField(
            model_name='pushnotificationlog',
            name='guard_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notifications', to='security.guardalert'),
        ),
        migrations.AddField(
            model_name='pushnotificationlog',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notifications', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='pushnotificationlog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pushnotificationlog',
            index=models.Index(fields=['recipient', '-queued_at'], name='accounts_pu_recipie_b75d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationlog',
            index=models.Index(fields=['notification_type', '-queued_at'], name='accounts_pu_notific_66cfda_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationlog',
            index=models.Index(fields=['status', '-queued_at'], name='accounts_pu_status_2b2cde_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationlog',
            index=models.Index(fields=['incident', '-queued_at'], name='accounts_pu_inciden_84472a_idx'),
        ),
    ]
