# Generated by Django 5.2.6 on 2026-01-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pushnotificationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='10-digit Indian phone number', max_length=10, null=True),
        ),
    ]
