# Generated by Django 5.2.6 on 2026-01-16 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('FIRE_ALERT', '🔥 Fire Alert'), ('THREAT_ALERT', '⚠️ Threat Alert'), ('LOCKDOWN', '🔒 Lockdown'), ('EVACUATION', '🚪 Evacuation'), ('SUSPICIOUS_ACTIVITY', '🕵️ Suspicious Activity'), ('WEATHER_WARNING', '⛈️ Weather Warning'), ('FACILITY_ISSUE', '🔧 Facility Issue'), ('TRAINING_ALERT', '📚 Training Alert'), ('SYSTEM_TEST', '🧪 System Test'), ('CUSTOM', '💬 Custom Message')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('target_all_guards', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_broadcast_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('invalid_token', 'Invalid Token')], db_index=True, default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='accounts.broadcastnotification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_broadcast_notification_log',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='broadcastnotification',
            index=models.Index(fields=['created_by', '-created_at'], name='accounts_br_created_59d427_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastnotification',
            index=models.Index(fields=['status', '-created_at'], name='accounts_br_status_5c445c_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastnotificationlog',
            index=models.Index(fields=['broadcast', 'status'], name='accounts_br_broadca_8ea206_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastnotificationlog',
            index=models.Index(fields=['recipient', '-queued_at'], name='accounts_br_recipie_6aae55_idx'),
        ),
    ]
