# Generated by Django 5.0 on 2026-03-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_broadcastnotification_broadcastnotificationlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotificationlog',
            name='broadcast',
        ),
        migrations.RemoveField(
            model_name='broadcastnotificationlog',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='BroadcastNotification',
        ),
        migrations.DeleteModel(
            name='BroadcastNotificationLog',
        ),
    ]
