# Generated by Django 5.2.6 on 2025-12-23 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(help_text='Distance from guard to incident in kilometers')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], db_index=True, default='SENT', max_length=20)),
                ('priority_rank', models.IntegerField(default=1, help_text='1=nearest, 2=second nearest, etc')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority_rank', '-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='last_known_latitude',
            field=models.FloatField(blank=True, help_text="Guard's last known latitude", null=True),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='last_known_longitude',
            field=models.FloatField(blank=True, help_text="Guard's last known longitude", null=True),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='guardprofile',
            index=models.Index(fields=['is_active'], name='security_gu_is_acti_b237b1_idx'),
        ),
        migrations.AddField(
            model_name='guardalert',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='security.guardprofile'),
        ),
        migrations.AddField(
            model_name='guardalert',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_alerts', to='incidents.incident'),
        ),
        migrations.AddIndex(
            model_name='guardalert',
            index=models.Index(fields=['incident', 'status'], name='security_gu_inciden_e554d6_idx'),
        ),
        migrations.AddIndex(
            model_name='guardalert',
            index=models.Index(fields=['guard', 'status'], name='security_gu_guard_i_16e37c_idx'),
        ),
        migrations.AddIndex(
            model_name='guardalert',
            index=models.Index(fields=['status', '-sent_at'], name='security_gu_status_1d25ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardalert',
            constraint=models.UniqueConstraint(fields=('incident', 'guard'), name='unique_guard_incident_alert'),
        ),
    ]
