# Generated by Django 5.2.6 on 2025-12-23 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_beacon_incidents_b_uuid_3c0cb1_idx_and_more'),
        ('security', '0002_guardalert_guardprofile_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardprofile',
            name='last_known_latitude',
        ),
        migrations.RemoveField(
            model_name='guardprofile',
            name='last_known_longitude',
        ),
        migrations.RemoveField(
            model_name='guardprofile',
            name='last_location_update',
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='current_beacon',
            field=models.ForeignKey(blank=True, help_text='Which beacon the guard is near (indoor location)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guards_present', to='incidents.beacon'),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='last_beacon_update',
            field=models.DateTimeField(blank=True, help_text="When guard's beacon was last updated", null=True),
        ),
        migrations.AlterField(
            model_name='guardprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Guard is on duty'),
        ),
        migrations.AlterField(
            model_name='guardprofile',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Guard is available for incidents'),
        ),
        migrations.AlterField(
            model_name='guardprofile',
            name='last_active_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last activity timestamp'),
        ),
        migrations.AddIndex(
            model_name='guardprofile',
            index=models.Index(fields=['current_beacon'], name='security_gu_current_3370ee_idx'),
        ),
    ]
