# Generated by Django 5.2.6 on 2025-12-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_beaconincident_panicbuttonincident_reportedincident'),
        ('security', '0003_remove_guardprofile_last_known_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardalert',
            name='beacon_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_alerts', to='incidents.beaconincident'),
        ),
        migrations.AddField(
            model_name='guardalert',
            name='panic_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_alerts', to='incidents.panicbuttonincident'),
        ),
        migrations.AddField(
            model_name='guardalert',
            name='reported_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_alerts', to='incidents.reportedincident'),
        ),
        migrations.AddField(
            model_name='guardassignment',
            name='beacon_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_assignments', to='incidents.beaconincident'),
        ),
        migrations.AddField(
            model_name='guardassignment',
            name='panic_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_assignments', to='incidents.panicbuttonincident'),
        ),
        migrations.AddField(
            model_name='guardassignment',
            name='reported_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_assignments', to='incidents.reportedincident'),
        ),
        migrations.AlterField(
            model_name='guardalert',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_alerts', to='incidents.incident'),
        ),
        migrations.AlterField(
            model_name='guardassignment',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_assignments', to='incidents.incident'),
        ),
    ]
