# Generated by Django 5.2.6 on 2025-12-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incidentsignal_remove_beaconincident_beacon_and_more'),
        ('security', '0004_guardalert_beacon_incident_guardalert_panic_incident_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardalert',
            options={'ordering': ['priority_rank', '-alert_sent_at']},
        ),
        migrations.RemoveConstraint(
            model_name='guardalert',
            name='unique_guard_incident_alert',
        ),
        migrations.RemoveConstraint(
            model_name='guardassignment',
            name='unique_active_guard_incident_assignment',
        ),
        migrations.RemoveIndex(
            model_name='guardalert',
            name='security_gu_status_1d25ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='guardassignment',
            name='security_gu_is_acti_c382b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='guardassignment',
            name='security_gu_inciden_61a3e7_idx',
        ),
        migrations.RenameField(
            model_name='guardalert',
            old_name='sent_at',
            new_name='alert_sent_at',
        ),
        migrations.RemoveField(
            model_name='guardalert',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='guardalert',
            name='beacon_incident',
        ),
        migrations.RemoveField(
            model_name='guardalert',
            name='panic_incident',
        ),
        migrations.RemoveField(
            model_name='guardalert',
            name='reported_incident',
        ),
        migrations.RemoveField(
            model_name='guardassignment',
            name='beacon_incident',
        ),
        migrations.RemoveField(
            model_name='guardassignment',
            name='panic_incident',
        ),
        migrations.RemoveField(
            model_name='guardassignment',
            name='reported_incident',
        ),
        migrations.AddField(
            model_name='guardalert',
            name='assignment',
            field=models.OneToOneField(blank=True, help_text='Assignment created when this alert was acknowledged', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert', to='security.guardassignment'),
        ),
        migrations.AlterField(
            model_name='guardalert',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Distance from guard to incident', null=True),
        ),
        migrations.AlterField(
            model_name='guardalert',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardalert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guardalert',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_alerts', to='incidents.incident'),
        ),
        migrations.AlterField(
            model_name='guardalert',
            name='priority_rank',
            field=models.IntegerField(help_text='1=nearest, 2=second nearest, etc', null=True),
        ),
        migrations.AlterField(
            model_name='guardassignment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_assignments', to='incidents.incident'),
        ),
        migrations.AddIndex(
            model_name='guardalert',
            index=models.Index(fields=['incident', 'guard', '-alert_sent_at'], name='security_gu_inciden_499d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='guardassignment',
            index=models.Index(fields=['incident', 'is_active'], name='security_gu_inciden_d3daea_idx'),
        ),
        migrations.AddIndex(
            model_name='guardassignment',
            index=models.Index(fields=['guard', 'is_active', '-assigned_at'], name='security_gu_guard_i_621da6_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardalert',
            constraint=models.UniqueConstraint(fields=('incident', 'guard'), name='unique_guard_per_incident_alert'),
        ),
        migrations.AddConstraint(
            model_name='guardassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('incident',), name='one_active_assignment_per_incident'),
        ),
    ]
