# Generated by Django 5.2.6 on 2026-01-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_guardalert_alert_type_requires_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='guardalert',
            name='security_gu_inciden_e554d6_idx',
        ),
        migrations.RenameIndex(
            model_name='guardalert',
            new_name='security_gu_inciden_0f1813_idx',
            old_name='security_guardalert_incident_alert_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='guardalert',
            new_name='security_gu_require_6e0f87_idx',
            old_name='security_guardalert_requires_response_status_idx',
        ),
        migrations.AddField(
            model_name='guardalert',
            name='decline_reason',
            field=models.TextField(blank=True, help_text='Optional reason for declining'),
        ),
        migrations.AddField(
            model_name='guardalert',
            name='push_notification_delivered',
            field=models.BooleanField(default=False, help_text='Whether push was delivered'),
        ),
        migrations.AddField(
            model_name='guardalert',
            name='push_notification_error',
            field=models.TextField(blank=True, help_text='Error message if push failed'),
        ),
        migrations.AddField(
            model_name='guardalert',
            name='push_notification_sent',
            field=models.BooleanField(default=False, help_text='Whether push was sent'),
        ),
        migrations.AddField(
            model_name='guardalert',
            name='push_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardalert',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When guard accepted/declined', null=True),
        ),
        migrations.AlterField(
            model_name='guardalert',
            name='assignment',
            field=models.OneToOneField(blank=True, help_text='Assignment created when guard accepts (ASSIGNMENT type only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert', to='security.guardassignment'),
        ),
        migrations.DeleteModel(
            name='DeviceToken',
        ),
    ]
