# Generated by Django 5.2.6 on 2026-01-01 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_incident_assigned_at_incident_current_assigned_guard_and_more'),
        ('security', '0007_remove_devicetoken_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guardassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('guard',), name='one_active_assignment_per_guard'),
        ),
    ]
