# Generated by Django 5.2.6 on 2025-12-22 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('location_name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'location_name'],
                'indexes': [models.Index(fields=['uuid'], name='incidents_b_uuid_3c0cb1_idx'), models.Index(fields=['building', 'floor'], name='incidents_b_buildin_0b142a_idx')],
                'constraints': [models.UniqueConstraint(fields=('major', 'minor'), name='unique_beacon_major_minor')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned to Guard'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], db_index=True, default='CREATED', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], db_index=True, default=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beacon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.beacon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='incidents_i_created_c4c91a_idx'), models.Index(fields=['status', '-created_at'], name='incidents_i_status_3b7181_idx'), models.Index(fields=['student', '-created_at'], name='incidents_i_student_902e67_idx')],
            },
        ),
    ]
