# Generated by Django 5.2.6 on 2025-12-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='beacon',
            name='incidents_b_uuid_3c0cb1_idx',
        ),
        migrations.AddField(
            model_name='beacon',
            name='beacon_id',
            field=models.CharField(blank=True, db_index=True, help_text='Hardware beacon ID (UUID:major:minor)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beacon',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Is beacon operational'),
        ),
        migrations.AddField(
            model_name='beacon',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Fixed beacon latitude', null=True),
        ),
        migrations.AddField(
            model_name='beacon',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Fixed beacon longitude', null=True),
        ),
        migrations.AddField(
            model_name='beacon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='building',
            field=models.CharField(help_text='e.g., Building A, Science Center', max_length=255),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='floor',
            field=models.IntegerField(help_text='Floor number'),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='location_name',
            field=models.CharField(help_text='e.g., Library Entrance, Hallway 3A', max_length=255),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='major',
            field=models.IntegerField(help_text='iBeacon major value'),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='minor',
            field=models.IntegerField(help_text='iBeacon minor value'),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='uuid',
            field=models.CharField(db_index=True, help_text='iBeacon UUID', max_length=36),
        ),
        migrations.AddIndex(
            model_name='beacon',
            index=models.Index(fields=['beacon_id'], name='incidents_b_beacon__3269bd_idx'),
        ),
        migrations.AddIndex(
            model_name='beacon',
            index=models.Index(fields=['uuid', 'major', 'minor'], name='incidents_b_uuid_e9ed96_idx'),
        ),
        migrations.AddIndex(
            model_name='beacon',
            index=models.Index(fields=['is_active'], name='incidents_b_is_acti_6ca5cd_idx'),
        ),
    ]
