# Generated by Django 5.2.6 on 2025-12-24 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_beacon_incidents_b_uuid_3c0cb1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, help_text='ESP32 device identifier', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='Device location name (e.g., Library Entrance)', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beacon', models.ForeignKey(help_text='Location of this panic button', on_delete=django.db.models.deletion.PROTECT, related_name='esp32_devices', to='incidents.beacon')),
            ],
            options={
                'ordering': ['device_id'],
                'indexes': [models.Index(fields=['device_id'], name='incidents_e_device__9973cf_idx'), models.Index(fields=['beacon'], name='incidents_e_beacon__5db913_idx'), models.Index(fields=['is_active'], name='incidents_e_is_acti_f0b387_idx')],
            },
        ),
    ]
