# Generated by Django 5.2.6 on 2025-12-24 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_esp32device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned to Guard'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], db_index=True, default='CREATED', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], db_index=True, default=2)),
                ('description', models.TextField(blank=True, help_text='Optional: Incident details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beacon', models.ForeignKey(help_text='Required: Beacon that triggered this incident', on_delete=django.db.models.deletion.PROTECT, related_name='beacon_incidents', to='incidents.beacon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beacon_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beacon Incident',
                'verbose_name_plural': 'Beacon Incidents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='incidents_b_created_5310c3_idx'), models.Index(fields=['status', '-created_at'], name='incidents_b_status_75b2b8_idx'), models.Index(fields=['beacon', '-created_at'], name='incidents_b_beacon__fee639_idx')],
            },
        ),
        migrations.CreateModel(
            name='PanicButtonIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned to Guard'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], db_index=True, default='CREATED', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], db_index=True, default=2)),
                ('description', models.TextField(blank=True, help_text='Optional: Additional context', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('esp32_device', models.ForeignKey(help_text='ESP32 panic button that was pressed', on_delete=django.db.models.deletion.PROTECT, related_name='panic_incidents', to='incidents.esp32device')),
                ('student', models.ForeignKey(blank=True, help_text='Student who pressed the button (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panic_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panic Button Incident',
                'verbose_name_plural': 'Panic Button Incidents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='incidents_p_created_7d9080_idx'), models.Index(fields=['status', '-created_at'], name='incidents_p_status_afd9ad_idx'), models.Index(fields=['esp32_device', '-created_at'], name='incidents_p_esp32_d_bc6878_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportedIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned to Guard'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], db_index=True, default='CREATED', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], db_index=True, default=2)),
                ('description', models.TextField(help_text='Incident description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beacon', models.ForeignKey(blank=True, help_text='Optional: Beacon location where incident occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='incidents.beacon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reported Incident',
                'verbose_name_plural': 'Reported Incidents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='incidents_r_created_be9a69_idx'), models.Index(fields=['status', '-created_at'], name='incidents_r_status_5f3cd3_idx'), models.Index(fields=['student', '-created_at'], name='incidents_r_student_24d49d_idx')],
            },
        ),
    ]
