# Generated by Django 5.2.6 on 2025-12-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_remove_aievent_ai_engine_a_inciden_b03b81_idx_and_more'),
        ('incidents', '0004_beaconincident_panicbuttonincident_reportedincident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSignal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('STUDENT_SOS', 'Student SOS Report'), ('AI_VISION', 'AI Vision Detection'), ('AI_AUDIO', 'AI Audio Detection'), ('PANIC_BUTTON', 'Panic Button (ESP32)')], db_index=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-created_at'], 'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='incidents_i_student_902e67_idx',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='student',
        ),
        migrations.AddField(
            model_name='incident',
            name='first_signal_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_signal_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='beacon',
            field=models.ForeignKey(help_text='Location of emergency (mandatory)', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.beacon'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, help_text='Optional incident description'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['beacon', '-created_at'], name='incidents_i_beacon__8ad29b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['beacon', 'status', '-created_at'], name='incidents_i_beacon__2e5536_idx'),
        ),
        migrations.AddField(
            model_name='incidentsignal',
            name='ai_event',
            field=models.ForeignKey(blank=True, help_text='AI event that triggered signal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_signal', to='ai_engine.aievent'),
        ),
        migrations.AddField(
            model_name='incidentsignal',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentsignal',
            name='source_device',
            field=models.ForeignKey(blank=True, help_text='ESP32 device that triggered signal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_signals', to='incidents.esp32device'),
        ),
        migrations.AddField(
            model_name='incidentsignal',
            name='source_user',
            field=models.ForeignKey(blank=True, help_text='User who triggered signal (SOS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_signals', to=settings.AUTH_USER_MODEL),
        ),
    ]
