# Generated by Django 5.2.6 on 2025-12-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_remove_aievent_ai_engine_a_inciden_b03b81_idx_and_more'),
        ('chat', '0003_alter_message_options_and_more'),
        ('incidents', '0005_incidentsignal_remove_beaconincident_beacon_and_more'),
        ('security', '0005_alter_guardalert_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeaconIncident',
        ),
        migrations.DeleteModel(
            name='PanicButtonIncident',
        ),
        migrations.DeleteModel(
            name='ReportedIncident',
        ),
        migrations.AddIndex(
            model_name='incidentsignal',
            index=models.Index(fields=['incident', '-created_at'], name='incidents_i_inciden_a76434_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentsignal',
            index=models.Index(fields=['signal_type', '-created_at'], name='incidents_i_signal__8619b0_idx'),
        ),
    ]
