# Generated by Django 5.2.6 on 2025-12-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_delete_beaconincident_delete_panicbuttonincident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='first_signal_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='last_signal_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
