# Generated by Django 5.2.6 on 2025-12-24 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_alter_incident_first_signal_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconProximity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(db_index=True, default=1, help_text='Lower number = higher priority (1 = nearest/same floor, 2 = adjacent floor, 3+ = far zones)')),
                ('from_beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity_from', to='incidents.beacon')),
                ('to_beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity_to', to='incidents.beacon')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='beacon',
            name='nearby_beacons',
            field=models.ManyToManyField(help_text='Nearby beacons in priority order for guard search expansion', related_name='nearby_from', through='incidents.BeaconProximity', to='incidents.beacon'),
        ),
        migrations.AddIndex(
            model_name='beaconproximity',
            index=models.Index(fields=['from_beacon', 'priority'], name='incidents_b_from_be_c9e601_idx'),
        ),
        migrations.AddConstraint(
            model_name='beaconproximity',
            constraint=models.UniqueConstraint(fields=('from_beacon', 'to_beacon'), name='unique_beacon_pair'),
        ),
    ]
