# Generated by Django 5.2.6 on 2025-12-26 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_beaconproximity_beacon_nearby_beacons_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, help_text='Location description if different from beacon', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='report_type',
            field=models.CharField(blank=True, help_text='Type of report (e.g., Safety Concern, Suspicious Activity, Infrastructure Issue)', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentsignal',
            name='signal_type',
            field=models.CharField(choices=[('STUDENT_SOS', 'Student SOS Report'), ('STUDENT_REPORT', 'Student General Report'), ('AI_VISION', 'AI Vision Detection'), ('AI_AUDIO', 'AI Audio Detection'), ('PANIC_BUTTON', 'Panic Button (ESP32)')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Incident photo/screenshot', upload_to='incidents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Image caption (optional)', max_length=255)),
                ('incident', models.ForeignKey(help_text='Incident this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='incidents.incident')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Image',
                'verbose_name_plural': 'Incident Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
