# Generated by Django 5.2.6 on 2025-12-30 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_incident_location_incident_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32device',
            name='device_type',
            field=models.CharField(choices=[('PANIC_BUTTON', 'Panic Button'), ('AI_VISION', 'AI Vision Detection'), ('AI_AUDIO', 'AI Audio Detection')], db_index=True, default='PANIC_BUTTON', help_text='Type of device: Panic button, AI vision, or AI audio', max_length=50),
        ),
        migrations.AlterField(
            model_name='esp32device',
            name='beacon',
            field=models.ForeignKey(help_text='Location where this device is situated', on_delete=django.db.models.deletion.PROTECT, related_name='esp32_devices', to='incidents.beacon'),
        ),
        migrations.AlterField(
            model_name='esp32device',
            name='device_id',
            field=models.CharField(db_index=True, help_text='Device identifier (e.g., ESP32-001, AI-VISION-01)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='incidentsignal',
            name='signal_type',
            field=models.CharField(choices=[('STUDENT_SOS', 'Student SOS Report'), ('STUDENT_REPORT', 'Student General Report'), ('VIOLENCE_DETECTED', 'Violence Detected'), ('SCREAM_DETECTED', 'Scream Detected'), ('PANIC_BUTTON', 'Panic Button (ESP32)')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='esp32device',
            index=models.Index(fields=['device_type'], name='incidents_e_device__2b9981_idx'),
        ),
    ]
