# Generated by Django 5.2.6 on 2025-12-30 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_esp32_to_physical(apps, schema_editor):
    """Copy data from ESP32Device to PhysicalDevice."""
    ESP32Device = apps.get_model('incidents', 'ESP32Device')
    PhysicalDevice = apps.get_model('incidents', 'PhysicalDevice')
    
    for device in ESP32Device.objects.all():
        PhysicalDevice.objects.create(
            id=device.id,
            device_id=device.device_id,
            device_type=device.device_type,
            beacon=device.beacon,
            name=device.name,
            is_active=device.is_active,
            created_at=device.created_at,
            updated_at=device.updated_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_add_device_type_to_esp32device'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, help_text='Device identifier (e.g., ESP32-001, AI-VISION-01)', max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('PANIC_BUTTON', 'Panic Button'), ('AI_VISION', 'AI Vision Detection'), ('AI_AUDIO', 'AI Audio Detection')], db_index=True, default='PANIC_BUTTON', help_text='Type of device: Panic button, AI vision, or AI audio', max_length=50)),
                ('name', models.CharField(blank=True, help_text='Device location name (e.g., Library Entrance)', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beacon', models.ForeignKey(help_text='Location where this device is situated', on_delete=django.db.models.deletion.PROTECT, related_name='physical_devices', to='incidents.beacon')),
            ],
            options={
                'ordering': ['device_id'],
            },
        ),
        migrations.RunPython(copy_esp32_to_physical),
        migrations.AlterField(
            model_name='incidentsignal',
            name='source_device',
            field=models.ForeignKey(blank=True, help_text='Physical device that triggered signal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_signals', to='incidents.physicaldevice'),
        ),
        migrations.RemoveField(
            model_name='esp32device',
            name='beacon',
        ),
        migrations.DeleteModel(
            name='ESP32Device',
        ),
        migrations.AddIndex(
            model_name='physicaldevice',
            index=models.Index(fields=['device_id'], name='incidents_p_device__5ffe9b_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaldevice',
            index=models.Index(fields=['device_type'], name='incidents_p_device__8a9b14_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaldevice',
            index=models.Index(fields=['beacon'], name='incidents_p_beacon__c5262f_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaldevice',
            index=models.Index(fields=['is_active'], name='incidents_p_is_acti_0c8c0a_idx'),
        ),
    ]
