# Generated by Django 5.2.6 on 2026-01-01 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_rename_esp32device_to_physicaldevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='current_assigned_guard',
            field=models.ForeignKey(blank=True, help_text='Currently assigned guard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notes about how incident was resolved'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('RESOLVED_BY_GUARD', 'Resolved by Guard'), ('ESCALATED_TO_ADMIN', 'Escalated to Admin')], help_text='How the incident was resolved', max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Guard/Admin who resolved this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='total_alerts_declined',
            field=models.PositiveIntegerField(default=0, help_text='Total alerts declined by guards'),
        ),
        migrations.AddField(
            model_name='incident',
            name='total_alerts_sent',
            field=models.PositiveIntegerField(default=0, help_text='Total alerts sent to guards'),
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INCIDENT_CREATED', 'Incident Created'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('ALERT_SENT', 'Alert Sent to Guard'), ('ALERT_DELIVERED', 'Push Notification Delivered'), ('ALERT_FAILED', 'Push Notification Failed'), ('ALERT_ACCEPTED', 'Guard Accepted Alert'), ('ALERT_DECLINED', 'Guard Declined Alert'), ('ALERT_EXPIRED', 'Alert Expired (No Response)'), ('GUARD_ASSIGNED', 'Guard Assigned'), ('GUARD_UNASSIGNED', 'Guard Unassigned'), ('RESOLUTION_STARTED', 'Resolution Started'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('ESCALATED_NO_RESPONSE', 'Escalated - No Response'), ('ALL_GUARDS_EXHAUSTED', 'All Guards Exhausted')], db_index=True, max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('previous_priority', models.IntegerField(blank=True, null=True)),
                ('new_priority', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Flexible metadata for event')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_events_triggered', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='incidents.incident')),
                ('target_guard', models.ForeignKey(blank=True, help_text='Guard targeted by this event (for alerts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_events_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Event',
                'verbose_name_plural': 'Incident Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident', '-created_at'], name='incidents_i_inciden_40cc14_idx'), models.Index(fields=['event_type', '-created_at'], name='incidents_i_event_t_3d13f3_idx'), models.Index(fields=['actor', '-created_at'], name='incidents_i_actor_i_82d7d7_idx'), models.Index(fields=['target_guard', '-created_at'], name='incidents_i_target__7339e6_idx')],
            },
        ),
    ]
