# Generated by Django 5.2.6 on 2026-01-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_incident_assigned_at_incident_current_assigned_guard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='buzzer_last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time buzzer status was changed'),
        ),
        migrations.AddField(
            model_name='incident',
            name='buzzer_status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive (No Incident)'), ('PENDING', 'Pending (Incident Created, No Guard Yet)'), ('ACTIVE', 'Active (Incident Assigned to Guard)'), ('ACKNOWLEDGED', 'Acknowledged (Guard En Route)'), ('RESOLVED', 'Resolved (Incident Complete)')], db_index=True, default='INACTIVE', help_text='Current buzzer status for ESP32 devices at this beacon', max_length=20),
        ),
    ]
